purbeurre_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from substitute import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^substitute/', include('substitute.urls', namespace="substitute")),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', auth_views.LoginView.as_view(template_name="substitute/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page="index"), name="logout"),
    url(r'^my_account/$', views.my_account, name="my_account"),
    url(r'^notices/$', views.notices, name="notices"),
    url(r'^control/', admin.site.urls)
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

substitute/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.results, name="results"),
    url(r'^(?P<product_id>[0-9]+)/$', views.details, name="details"),
    url(r'^ajax/save_product/$', views.save_product, name="save_product"),
    url(r'^ajax/delete_product/$', views.delete_product, name="delete_product"),
    url(r'^my_products/$', views.my_products, name="my_products")
]

substitute/models.py
from django.db.models import Model, BigIntegerField, CharField, ManyToManyField, ForeignKey, CASCADE
from django.contrib.auth.models import User


class Product(Model):
    code = BigIntegerField("code produit", unique=True, null=True)
    name = CharField("nom", max_length=200)
    nutriscore = CharField("nutriscore", max_length=10, null=True)
    url_picture = CharField("image", max_length=200, null=True)
    users = ManyToManyField(User, related_name="products")

    class Meta:
        verbose_name = "produit"

    def __str__(self):
        return self.name

class Query(Model):
    name = CharField("requete", max_length=200)
    user = ForeignKey(User, on_delete=CASCADE)
    product = ForeignKey(Product, on_delete=CASCADE, null=True)

    class Meta:
        verbose_name = "requetes"

    def __str__(self):
        return self.name

substitute/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

substitute/views.py
import re
import html
import logging

import requests
from django.db import transaction, IntegrityError
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .forms import SignUpForm
from .models import Product, Query
from .libs.exceptions import NoProductError
from .libs.api_interactions import Substitutes, DataApiClient


logger = logging.getLogger(__name__)

def index(request):
    """ Home page of Pur Beurre """

    return render(request, "substitute/index.html")

def results(request):
    """ Page with results of a request """

    query = request.GET.get("query")
    request.session["query"] = query
    try:
        substitutes = Substitutes(query=query)
        substitutes_request = substitutes.get_substitutes()
        # I use session to store the results of the user query
        request.session["substitutes"] = substitutes_request
        substitutes_list = []
        for product in substitutes_request:
            image_url = product.get("image_url", "")
            nutriscore = product.get("nutrition_grade_fr", "")
            if (image_url != "") and (nutriscore != ""):
                substitute = {
                    "name": product.get("product_name_fr", "Nom non renseigné"),
                    "nutriscore": product["nutrition_grade_fr"],
                    "picture": product["image_url"],
                    "id_product": product["code"]
                }
                substitutes_list.append(substitute)

        paginator = Paginator(substitutes_list, 12)
        page = request.GET.get("page")
        try:
            substitutes_results = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            substitutes_results = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results
            substitutes_results = paginator.page(paginator.num_pages)

        context = {
            "query": query,
            "substitutes": substitutes_results,
            "count": len(substitutes_list),
            'paginate': True
        }
    except NoProductError:
        context = {
            "query": query,
            "substitutes": [],
            "count": 0,
            'paginate': False
        }
        logger.info('No products found', exc_info=True, extra={
        # Optionally pass a request and we'll grab any information we can
        'request': request,
        })

    return render(request, "substitute/results.html", context)    

def details(request, product_id):
    """ Page with details of a selected substitute """
    
    # I check if a product is already saved by a user.
    # The button to save will be disabled if the relation already exists
    # between a user and a product.
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user)
        existing_relation = user.products.filter(code=product_id).exists()
    else:
        existing_relation = False
    
    if existing_relation:
        associated_query = Query.objects.get(product__code=product_id,
                                        user = user.id).name
    else:
        associated_query = False

    try:
        selected_product = [substitute
                            for substitute in request.session["substitutes"]
                            if substitute["code"] == product_id]
        if selected_product:
            substitute = selected_product[0]
            context = {
                "code": substitute["code"],
                "name": substitute.get("product_name_fr"),
                "nutriscore": substitute.get("nutrition_grade_fr", ""),
                "picture": substitute.get("image_url"),
                "ingredients": substitute.get("ingredients_text_with_allergens_fr", ""),
                "nutrition_picture": substitute.get("image_nutrition_url", ""),
                "stores": substitute.get("stores"),
                "already_saved": existing_relation,
                "query": associated_query
            }
        else:
            raise KeyError
    except KeyError:
        # When a session expired or didn't exists before,
        # the list of substitutes is lost or not exist.
        # exceptionally I make a request to the API to find a product when the
        # session does not have a substitute list or if the product isn't in it.
        api_request = DataApiClient(product_id = product_id)
        product = api_request.get_product()
        context = {
            "code": product["code"],
            "name": product.get("product_name_fr"),
            "nutriscore": product.get("nutrition_grade_fr", ""),
            "picture": product.get("image_url"),
            "ingredients": product.get("ingredients_text_with_allergens_fr"),
            "nutrition_picture": product.get("image_nutrition_url", ""),
            "stores": product.get("stores"),
            "already_saved": existing_relation,
            "query": associated_query
        }
        logger.warning('Product not in session, a call to API is made', exc_info=True, extra={
        # Optionally pass a request and we'll grab any information we can
        'request': request,
        })

    return render(request, "substitute/details.html", context)

@transaction.atomic
def save_product(request):
    """ To save a product in a user account """
    if request.method == "POST":
        user = get_object_or_404(User, username=request.user)
        # I check if the product is already in the data base or not.
        if not Product.objects.filter(code=request.POST.get("code")).exists():
            try:
                with transaction.atomic():
                    product = Product(
                        code = request.POST.get("code", ""),
                        # To decode specials strings
                        name = html.unescape(request.POST.get("name", "")),
                        nutriscore = request.POST.get("nutriscore", ""),
                        url_picture = request.POST.get("picture", ""),
                    )
                    product.save()
                    query = Query(
                        name = request.session["query"],
                        user = user,
                        product = product)
                    query.save()
                logger.info('New product registered in database', exc_info=True, extra={
                # Optionally pass a request and we'll grab any information we can
                'request': request,
                })
                data = {
                    "new_product": True
                }
            except IntegrityError:
                data = {
                    "error": True
                }
        else:
            try:
                with transaction.atomic():
                    product = Product.objects.get(code=request.POST.get("code"))
                    query = Query(
                        name = request.session["query"],
                        user = user,
                        product = product)
                    query.save()
                    data = {
                        "product_exists": True
                    }
            except IntegrityError:
                data = {
                    "error": True
                }                

        try:
            with transaction.atomic():
                product.users.add(user)
        except IntegrityError:
            data = {
                "error": True
            }                
    else:
        raise Http404("Cette page n'est pas accessible.")

    return JsonResponse(data)

@transaction.atomic
def delete_product(request):
    """ To delete a product from a user account """

    if request.method == 'POST':
        user = get_object_or_404(User, username=request.user)
        try:
            with transaction.atomic():
                product = Product.objects.get(code=request.POST.get("code"))
                product.users.remove(user)
                query = Query.objects.get(user=user.id, product=product.id)
                query.delete()
                data = {
                    "delete": True,
                }
        except:
            data = {
                "error": True
            }
    else:
        raise Http404("Cette page n'est pas accessible.")

    return JsonResponse(data)

def my_products(request):
    """ Page to display the products saved by users """

    user = get_object_or_404(User, username=request.user)
    products = user.products.all().order_by("name")
    products_list = []
    for product in products:
        my_product = {
            "name": product.name,
            "nutriscore": product.nutriscore,
            "picture": product.url_picture,
            "id_product": product.code,
        }
        products_list.append(my_product)
    paginator = Paginator(products_list, 12)
    page = request.GET.get("page")
    try:
        products_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products_page = paginator.page(paginator.num_pages)

    context = {
        "query": "Mes produits",
        "substitutes": products_page,
        "count": len(products_list),
        'paginate': True,
        "my_products": True
    }

    return render(request, "substitute/results.html", context)

def signup(request):
    """ Page to sign up """

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

substitute/templates/substitute/account.html
{% extends "substitute/base.html" %}

{% block title %}

    {{ title }}

{% endblock %}


{% block header %}

    {% include 'substitute/header.html' with title=title %}

{% endblock %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">
                <div class="offset-md-4">
                    <div class="row">
                        <h4 class="col-md-6 text-right">Username:</h4>
                        <h4 class="col-md-6"> {{ username }}</h4>
                    </div>
                    <div class="row">
                            <h4 class="col-md-6 text-right">Email:</h4>
                            <h4 class="col-md-6"> {{ email }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock  %}

substitute/templates/substitute/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Cette plateforme web permet de trouver des aliments de meilleur qualité que ceux que l'on mange au quotiduen">
    <meta name="author" content="">

    <title>{% block title %}Pur Beurre{% endblock %}</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'substitute/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    
    <!-- Custom fonts for this template -->
    <link href="{% static 'substitute/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Custom glyph for this template -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <!-- Plugin CSS -->
    <link type="text/css" href="{% static 'substitute/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link type="text/css" href="{% static 'substitute/css/creative.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'substitute/img/logo_pur_beurre.png' %}" style="height:30px; width:30px" alt="logo"> Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <form action="{% url 'substitute:results' %}" method="get" accept-charset="utf-8">
                <label for="navsearch" style="display:none">Chercher</label>
                <input type="text" name="query" class="form-control form-control-sm" id="navsearch" placeholder="Chercher">
              </form>
            </li>
          
            {% if not user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" id="login" href="{% url 'login' %}"><i class="fas fa-lock"></i> Connexion</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" id="account" href="{% url 'my_account' %}"><i class="fas fa-user"></i> Mon Compte</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" id="products" href="{% url 'substitute:my_products' %}"><img src="{% static 'substitute/img/carotte.png' %}" style="height:20px; width:20px" alt="menu">Mes Produits</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" id="logout" href="{% url 'logout'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
                </li> 
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    {% block header %}{% endblock %}

    {% block content %}{% endblock content %}

    <footer>
        <div class="container py-2">
            <div class="row justify-content-around">
              <div class="col-4 text-center">
                <a href="{% url 'notices' %}">Mentions légales</a>
              </div>
              <div class="col-4 text-center">
                <a href="/#contact">Contact</a>
              </div>
            </div>
        </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'substitute/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'substitute/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'substitute/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'substitute/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'substitute/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'substitute/js/creative.min.js' %}"></script>

    <!-- JQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    {% block javascript %}{% endblock  %}

  </body>

</html>

substitute/templates/substitute/details.html
{% extends 'substitute/base.html' %}

{% block title %}
    {{ name }}
{% endblock %}

{% block header %}
    {% include 'substitute/header.html' with title=name %}
{% endblock %}

{% block content %}

<section id="details">
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-12 text-center">
                <img class="img-responsive rounded my-2" id="nutriscore-picture" src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ nutriscore }}.svg" alt="Nutriscore: {{ nutriscore }}">
            </div>
            <div class="col-sm-12 text-center">
                <a href="https://fr.openfoodfacts.org/score-nutritionnel-experimental-france"><i class="fas fa-info-circle"></i> Plus d'informations</a>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-6 text-center my-auto">
                <img class="img-responsive rounded my-2" id="product-picture" src="{{ picture }}" alt="{{ name }}">
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div id="ingredients" class="col-sm-12 text-left">
                        <h6>
                            <span style="text-decoration: underline">Liste des ingrédients:</span> <br>
                            {% autoescape off %}
                            {{ ingredients }}
                            {% endautoescape %}
                        </h6>
                    </div>
                    <div class="col-sm-12">
                        <img class="img-responsive rounded my-2" id="nutrition-picture" src="{{ nutrition_picture }}">
                    </div>
                </div>
            </div>
        </div>
        {% if stores %}
        <div class="row mt-3" id="stores">
            <div class="col-sm-6 text-center">
                <h5>Où se procurer cet aliment ? <br> {{ stores }}</h5>
            </div>
        </div>
        {% endif %}
        {% if query %}
            <div class=class="row mt-3">
                <button class="mx-auto text-center btn btn-info" disabled>Produit enregistré pour remplacer:<br> <span id="associated_query">{{ query }}</span></button>
            </div>
        {% endif %}
        {% if already_saved %}
            <div class="row mt-2">
                <button class=" mx-auto btn btn-success" disabled>CE PRODUIT EST ENREGISTRÉ DANS VOTRE ESPACE</button>
            </div>
        {% else %}
            <div class="row mt-2">
                <button id="save" class=" mx-auto btn btn-primary">ENREGISTRER CE PRODUIT</button>
            </div>
        {% endif %}
    </div>
</section>

{% endblock %}

{% block javascript %}
    {% if user.is_authenticated %}
    <script>
    $(function() {
        // Allows to get cookie 'csrftoken'
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        // The token is use to secure the AJAX POST method
        $.ajaxSetup({   headers: {  "X-CSRFToken": csrftoken  }  });
        $("#save").click(function () {
            $.ajax({
                type: 'POST',
                url: '{% url "substitute:save_product" %}',
                data: {
                    'code': '{{code}}',
                    'name': '{{name}}',
                    'nutriscore': '{{nutriscore}}',
                    'picture': '{{picture}}',
                },
                dataType: 'json',
                success: function (data) {
                if ((data.new_product) || (data.product_exists) ) {
                    alert("Le produit à bien été enregistré dans votre espace personnel");
                    $("#save").toggleClass("btn-primary").toggleClass("btn-success").attr("disabled", true);
                    $("#save").text("CE PRODUIT EST ENREGISTRÉ DANS VOTRE ESPACE")
                }
                else if(data.error){
                    alert("Un problème est survenu veuillez recommencer");
                    }
                }
            }); 
        });
    });
    </script>
    {% else %}
    <script>
        $(function(){
            $("#save").click(function () {
                alert("Vous devez être connecté pour pouvoir enregistrer un produit");
            });
        });
    </script>
    {% endif %}
{% endblock %}

substitute/templates/substitute/header.html
<header class="headertemp text-center text-white d-flex">
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h1 class="text-uppercase" id="headerTitle">
            <strong >{{ title }}</strong>
          </h1>
        </div>
      </div>
    </div>
</header>

substitute/templates/substitute/login.html
{% extends 'substitute/base.html' %}

{% block title %}Connexion{% endblock  %}

{% block header %}

    {% include 'substitute/header.html' with title="Connexion" %}

{% endblock  %}


{% block content %}

  <section>
    <div class="container text-center">
        
        {% if form.errors %}
            <p id="login_error" style="color: red; font-weight: bold">Le nom d'utilisateur et le mot de passe ne correspondent pas.</p>
        {% endif %}
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.label }}" class="offset-sm-3 col-sm-3 col-form-label">{{ field.label }} :</label>
                    <div class="col-sm-6 text-left">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary" id="submitlogin" type="submit">Connexion</button>
        </form>
        <br>
        <p>
            Vous n'avez pas de compte ? <a id="signup" href="{% url 'signup' %}"> Cliquez ici</a>
        </p>
    </div>
</section>

{% endblock %}

substitute/templates/substitute/results.html
{% extends 'substitute/base.html' %}

{% block title %}
    Résultats pour {{ query }}
{% endblock %}


{% block header %}
    {% include 'substitute/header.html' with title=query %}
{% endblock %}


{% block content %}

<section class="container" id="substitutes">
    {% if not query %}
        <p class="text-center" style="font-weight: bold">Vous devez renseigner le nom d'un aliment</p>
    {% elif not substitutes %}
        <p id="count" style="font-style: italic">{{ count }} résultats</p>
        {% if my_products %}
            <p class="text-center" style="font-weight: bold">Vous n'avez pas encore enregistré de produits</p>
        {% else %}
            <p class="text-center" style="font-weight: bold">Nous n'avons pas trouvé de produits similaires à "{{ query }}"</p>
        {% endif %}
    {% else %}
        <p id="count" style="font-style: italic">{{ count }} résultats</p>
        {% if not my_products %}
            <h4 class="text-center" style="font-style:italic;">Voici les produits similaires à "{{ query }}" ayant la meilleure note nutritionnelle</h4>
        {% endif %}
        <div class="container text-center mt-5">
            <div class="row">
                {% for substitute in substitutes %}
                    <div class="col-sm-4 text-center">
                        <a href="{% url 'substitute:details' product_id=substitute.id_product %}" class="col-sm-12 substitute">
                                <img class="img-responsive rounded my-2" src="{{ substitute.picture }}" style="height:250px; width:150px" alt="{{ substitute.name }}">
                                <img class="result-nutriscore" src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ substitute.nutriscore }}.svg" alt="nutriscore">
                            <h5 style="font-weight:bold;">{{ substitute.name }}</h5>
                        </a>
                        {% if my_products %}
                            <button id="{{ substitute.id_product }}" class="delete_product mx-auto mb-3 btn">SUPPRIMER</button>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    
    {% if paginate %}
        {% if my_products %}
            <div class="mt-3">
                <nav aria-label="page navigation">
                    <ul class="pagination">
                        {% if substitutes.has_previous %}
                            <li><a class="btn btn-primary mx-1" href="/substitute/my_products/?page={{ substitutes.previous_page_number }}">Précédent</a></li>
                        {% endif %}
                        {% if substitutes.has_next %}
                            <li><a class="btn btn-primary mx-1" href="/substitute/my_products/?page={{ substitutes.next_page_number }}">Suivant</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% else %}
            <div class="mt-3">
                <nav aria-label="page navigation">
                    <ul class="pagination">
                        {% if substitutes.has_previous %}
                            <li><a class="btn btn-primary mx-1" href="/substitute/?query={{ query }}&page={{ substitutes.previous_page_number }}">Précédent</a></li>
                        {% endif %}
                        {% if substitutes.has_next %}
                            <li><a class="btn btn-primary mx-1" href="/substitute/?query={{ query }}&page={{ substitutes.next_page_number }}">Suivant</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    {% endif %}
</section>
{% endblock %}

{% block javascript %}
<script>
    $(function() {
        // Allows to get cookie 'csrftoken'
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        // The token is use to secure the AJAX POST method
        $.ajaxSetup({   headers: {  "X-CSRFToken": csrftoken  }  });
        var button_list = $(".delete_product");
        button_list.each(function(){
            $(this).click(function () {
                var conf = confirm("Êtes-vous sûr de vouloir supprimer ce produit ?");
                if (conf == true){
                    $.ajax({
                        type: 'POST',
                        url: '{% url "substitute:delete_product" %}',
                        data: {
                        'code': this.id,
                        },
                        dataType: 'json',
                        success: function (data) {
                        if (data.delete) {
                            alert("Le produit à bien été supprimé de votre espace personnel");
                            window.location.reload();
                        }
                        else if(data.error){
                            alert("Un problème est survenu veuillez recommencer");
                            }
                        }
                    }); 
                };
            });
        });
    });
</script>
{% endblock %}